In [1]:
import pandas as pd

df = pd.read_csv("Sample - Superstore.csv",sep=',', encoding='latin1')

#El formato de estas dos columnas están erroneas, las paso a formate Datetime:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

#Para hacer cálculos futuros separamos las fechas por mes y por año
df["Order Month Name"] = df["Order Date"].dt.month_name()
df["Order Year"] = df["Order Date"].dt.year

In [ ]:
#Vemos la suma de todos los años para analizar su evolcuión, si hubo crecimiento, si hubo algún año diferente...
df.groupby("Order Year")["Sales"].sum().round(2)

Order Year
2014    484247.50
2015    470532.51
2016    609205.60
2017    733215.26
Name: Sales, dtype: float64

In [ ]:
#Verificamos si todos los años tienen todos los meses para ver si realmente todos los años con comparables.
df.groupby("Order Year")["Order Month Name"].nunique()

In [ ]:
#Regiones por ventas y beneficios
df.groupby("Region")[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)

#Creamos una nueva columna con el beneficio porcentual para ver más exacto a que equivale ese beneficio con respecto a las ventas
df["Profit Margin"] = round((df['Profit']/df['Sales'])*100,2)
#Visualización de ventas vs cantidad beneficio vs % beneficio
df[["Sales", "Profit", "Profit Margin"]].head()

      Sales    Profit  Profit Margin
0  261.9600   41.9136          16.00
1  731.9400  219.5820          30.00
2   14.6200    6.8714          47.00
3  957.5775 -383.0310         -40.00
4   22.3680    2.5164          11.25

In [ ]:
#Agrupo por descuentos para ver como son los beneficios depende de los descuentos aplicados
df.groupby("Discount")[["Sales", "Profit", "Profit Margin"]].mean()

In [ ]:
#Calculamos la media de las tres columnas y agrupamos por la categoria para ver la media del margen de beneficio
df.groupby("Category")[["Sales", "Profit", "Profit Margin"]].mean()

                      Sales     Profit  Profit Margin
Category
Furniture        349.834887   8.699327       3.878326
Office Supplies  119.324101  20.327050      13.803032
Technology       452.709276  78.752002      15.613812

In [ ]:
#Ahora vemos la categoria y su descuento para ver que margen de beneficio tiene
df.groupby(["Category", "Discount"])["Profit Margin"].mean().reset_index()

           Category  Discount  Profit Margin
0         Furniture      0.00      29.001196
1         Furniture      0.10      13.158158
2         Furniture      0.15       3.417115
3         Furniture      0.20       7.158537
4         Furniture      0.30     -12.065946
5         Furniture      0.32     -17.429259
6         Furniture      0.40     -34.178133
7         Furniture      0.45     -45.455455
8         Furniture      0.50     -62.592593
9         Furniture      0.60     -68.913043
10        Furniture      0.70    -166.445333
11  Office Supplies      0.00      36.711090
12  Office Supplies      0.10      24.931250
13  Office Supplies      0.20      23.158791
14  Office Supplies      0.70     -74.508763
15  Office Supplies      0.80    -182.500000
16       Technology      0.00      28.925570
17       Technology      0.10      32.775000
18       Technology      0.20      11.052319
19       Technology      0.30      11.430000
20       Technology      0.40     -15.419924
21       Technology      0.50     -20.333333
22       Technology      0.70    -104.781739

In [2]:
#Top 10 ciudades

df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(10)

City
New York City    256368.1610
Los Angeles      175851.3410
Seattle          119540.7420
San Francisco    112669.0920
Philadelphia     109077.0130
Houston           64504.7604
Chicago           48539.5410
San Diego         47521.0290
Jacksonville      44713.1830
Springfield       43054.3420
Name: Sales, dtype: float64

In [3]:
#Ventas por año
df['Year'] = df['Order Date'].dt.year
df.groupby('Year')['Sales'].sum()

Year
2014    484247.4981
2015    470532.5090
2016    609205.5980
2017    733215.2552
Name: Sales, dtype: float64

In [4]:
#Top clientes
df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64